# Generated by Django 5.2.1 on 2026-06-11 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='姓名')),
                ('id_type', models.CharField(choices=[('id_card', '身份证'), ('passport', '护照'), ('hk_macau', '港澳通行证'), ('taiwan', '台湾通行证'), ('other', '其他')], default='id_card', max_length=20, verbose_name='证件类型')),
                ('id_number', models.CharField(max_length=50, verbose_name='证件号码')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('special_requirements', models.CharField(blank=True, max_length=300, verbose_name='特殊需求')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='bookings.booking')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
